== Message Metadata

A `Message` can have a set of metadata associated with it.

=== Retrieving metadata

You can retrieve the metadata from a message using either:

* `getMetadata(Class<?> c)` : get a specific type of metadata
* `getMetadata()` : allows iterate through the metadata (it also provides method to manipulate the set)

[source,java,indent=0]
----
include::example$messages/MetadataExamples.java[tag=extraction]
----

=== Adding metadata

Metadata associated with a message can be any object.
Note that only one instance of each class can be attached.
So, it is recommend to create specific class to store your metadata.
Also, because the metadata may be accessed concurrently, it is highly recommended to use immutable objects.

You can create a message with some metadata using `Message.of(payload, Metadata.of(...) )`

[source,java,indent=0]
----
include::example$messages/MetadataExamples.java[tag=creation]
----

You can also add metadata to an existing message using the `withMetadata` method.

=== Metadata propagation

When your are processing payloads, Reactive Messaging propagates the metadata through the stream.
So, it copies the metadata from the incoming message to the outgoing message.

[source,java,indent=0]
----
include::example$messages/MetadataWithPayloadChainExamples.java[tag=chain]
----

When dealing with `Message` or streams, the propagation is manual:

[source,java,indent=0]
----
include::example$messages/MetadataWithMessageChainExamples.java[tag=chain]
----

Consult the xref:signatures/signatures.adoc[signature list] to check which signature support automatic propagation.

