[#$CONNECTOR-inbound]
== Receiving messages from $CONNECTOR-NAME

TASK: Update title

The $CONNECTOR Connector retrieves $TYPE_OF_MESSAGE and maps each of them into Reactive Messaging `Messages`.

=== Example

Let's imagine you have a $BROKER running, and accessible using the `$URL` address (by default it would use `$DEFAULT_URL`).
Configure your application to receive {CHANGE THE TYPE OF MESSAGE} on the `prices` channel as follows:

[source]
----
$BASE_URL_PROPERTY=$URL      # <1> TASK: CHANGE HERE

mp.messaging.incoming.prices.connector=$CONNECTOR-NAME       # <2>
$OTHER_ATTRIBUTES    # <3>
----
1. Configure the broker location. You can configure it globally or per channel <-- TASK: CHANGE HERE
2. Sets the connector for the `prices` channel
3. TASK: Explain other attributes

NOTE: You don't need to set the $DESTINATION. By default, it uses the channel name (`prices`). You can configure the `$DESTINATION_ATTRIBUTE` attribute to override it.

Then, your application receives `Message<Double>`.
You can consumes the payload directly:

[source, java]
----
include::example$inbound/PriceConsumer.java[]
----

Or, you can retrieve the `Message<Double>`:

[source, java]
----
include::example$inbound/PriceMessageConsumer.java[]
----

=== Deserialization

TASK: Explain deserialization

=== Inbound Metadata

Messages coming from $TECHNOLOGY contains an instance of `$INBOUND_METADATA_CLASS` in the metadata.
TASK: What does it contain and potential type parameter:

[source, java]
----
include::example$inbound/MetadataExample.java[]
----

=== Acknowledgement

TASK: Explain acknowledgement

=== Configuration Reference

include::connectors:partial$META-INF/connector/CONNECTOR-NAME-incoming.adoc[]

TASK: Change the file name
TASK: Indicate if there is an underlying client that can be configured.
