[#$CONNECTOR-outbound]
== Sending messages to $CONNECTOR

TASK: Update title

The $CONNECTOR Connector can write Reactive Messaging `Messages` as $TYPE_OF_MESSAGE.

=== Example

Let's imagine you have a $BROKER} running, and accessible using the `$URL` address (by default it would use `$DEFAULT_URL`).
Configure your application to write the messages from the `prices` channel into a $TYPE_OF_MESSAGE as follows:

[source]
----
$BASE_URL_PROPERTY=$URL      # <1> TASK: CHANGE HERE

mp.messaging.incoming.prices.connector=$CONNECTOR-NAME       # <2>
$OTHER_ATTRIBUTES  # <3>
----
1. Configure the broker location. You can configure it globally or per channel <-- TASK: CHANGE HERE
2. Sets the connector for the `prices` channel
3. TASK: Explain other attributes

NOTE: You don't need to set the $DESTINATION. By default, it uses the channel name (`prices`). You can configure the `$DESTINATION_ATTRIBUTE` attribute to override it.

Then, your application must send `Message<Double>` to the `prices` channel.
It can use `double` payloads as in the following snippet:

[source, java]
----
include::example$outbound/PriceProducer.java[]
----

Or, you can send `Message<Double>`:

[source, java]
----
include::example$outbound/PriceMessageProducer.java[]
----

=== Serialization

TASK: Explain serialization

TASK: Explain the default structure of the sent message

=== Outbound Metadata

When sending `Messages`, you can add an instance of `$OUTBOUND_METADATA_CLASS` to influence how the message is going to written to $TECHNOLOGY.
TASK: What does it contain and potential type parameter:

[source, java]
----
include::example$outbound/OutboundMetadataExample.java[]
----

=== Acknowledgement

TASK: Explain acknowledgement

=== Configuration Reference

include::connectors:partial$META-INF/connector/CONNECTOR-NAME-outgoing.adoc[]

TASK: Change the file name
TASK: Indicate if there is an underlying client that can be configured.
