= Getting Started

== Quickstart

The easiest to start using SmallRye Reactive Messaging is to start it directly in a _main_ class.

Creates a Maven project, and include the following dependency in your pom.xml:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-provider</artifactId>
  <version>{project-version}</version>
</dependency>
<dependency>
 <groupId>io.smallrye.reactive</groupId>
 <artifactId>mutiny-reactive-streams-operators</artifactId>
 <version>{mutiny-version}</version>
</dependency>
<dependency>
  <groupId>org.jboss.weld.se</groupId>
  <artifactId>weld-se-core</artifactId>
  <version>{weld-version}</version>
</dependency>
<dependency>
  <groupId>io.smallrye.config</groupId>
  <artifactId>smallrye-config</artifactId>
  <version>{smallrye-config-version}</version>
</dependency>
----

Once created, create a class file with a `public static void main(String... args)` method:

[source,java]
----
include::example$quickstart/Main.java[]
----

This example use CDI SE, so a version compatible with regular (_i.e._ SE) Java.

Then, we need CDI _beans_. For instance:

[source, java]
----
include::example$quickstart/MyBean.java[]
----

Finally, you need an _empty_ `beans.xml`. Copy the following content to `src/main/resources/META-INF/beans.xml`:

[source,xml]
----
<beans
  xmlns="http://xmlns.jcp.org/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="
      http://xmlns.jcp.org/xml/ns/javaee
      http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd">

</beans>
----

Once everything is setup, you should be able to run the application using:

[source,bash]
----
mvn compile exec:java -Dexec.mainClass=quickstart.Main
----

Running the previous example should give the following output:

[source]
----
>> HELLO
>> SMALLRYE
>> REACTIVE
>> MESSAGE
----

[NOTE]
====
SmallRye Reactive Messaging uses JBoss-logging to log.

For testing purpose, you can simply add a `logging.properties` file in `${basedir}/src/main/resources/logging.properties`

Then run the application using:

[source,bash]
----
mvn package exec:java -Dexec.mainClass=quickstart.Main -Djava.util.logging.config.file=${basedir}/src/main/resources/logging.properties
----

Example logging.properties:

```
handlers= java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=[%1$tF %1$tT] [%4$-7s] %5$s %n

.level=OFF
acme.level=FINEST
```
====