[#mqtt-inbound]
== Receiving messages from MQTT

The MQTT Connector connects to a MQTT broker or router, and forward the messages to the Reactive Messaging application.
It maps each of them into Reactive Messaging `Messages`.

=== Example

Let's imagine you have a MQTT server/broker running, and accessible using the `mqtt:1883` address (by default it would use `localhost:1883`).
Configure your application to receive MQTT messages on the `prices` channel as follows:

[source]
----
mp.messaging.incoming.prices.connector=smallrye-mqtt       # <1>
mp.messaging.incoming.prices.host=mqtt                     # <2>
mp.messaging.incoming.prices.port=1883                     # <3>
----
1. Sets the connector for the `prices` channel
2. Configure the broker/server host name.
3. Configure the broker/server port. 1883 is the default.

NOTE: You don't need to set the MQTT topic. By default, it uses the channel name (`prices`). You can configure the `topic` attribute to override it.
NOTE: It is generally recommended to set the `client-id`. By default, the connector is generating a unique `client-id`.

IMPORTANT: Message coming from MQTT have a `byte[]` payload.

Then, your application receives `Message<byte[]>`.
You can consumes the payload directly:

[source, java]
----
include::example$inbound/MqttPriceConsumer.java[]
----

Or, you can retrieve the `Message<byte[]>`:

[source, java]
----
include::example$inbound/MqttPriceMessageConsumer.java[]
----

The inbound topic can use the https://mosquitto.org/man/mqtt-7.html[MQTT wildcards] (`+` and `#`).

=== Deserialization

The MQTT Connector does not handle the deserialization and creates a `Message<byte[]>`.

=== Inbound Metadata

The MQTT connector does not provide inbound metadata.

=== Failure Management

If a message produced from a MQTT message is _nacked_, a failure strategy is applied.
The MQTT connector supports 3 strategies:

* `fail` - fail the application, no more MQTT messages will be processed. (default)
The offset of the record that has not been processed correctly is not committed.
* `ignore` - the failure is logged, but the processing continue.

=== Configuration Reference

include::connectors:partial$META-INF/connector/smallrye-mqtt-incoming.adoc[]

The MQTT connector is based on the https://vertx.io/docs/vertx-mqtt/java/#_vert_x_mqtt_client[Vert.x MQTT client].
So you can pass any attribute supported by this client.

IMPORTANT: A single instance of `MqttClient` and a single connection is used for each `host` / `port` / `server-name` / `client-id`.
This client is reused for both the inbound and outbound connectors.
