[#mqtt-outbound]
== Sending messages to MQTT

The MQTT Connector can write Reactive Messaging `Messages` as MQTT Message.

=== Example

Let's imagine you have a MQTT server/broker running, and accessible using the `mqtt:1883` address (by default it would use `localhost:1883`).
Configure your application to write the messages from the `prices` channel into a MQTT Messages as follows:

[source]
----
mp.messaging.outgoing.prices.type=smallrye-mqtt  # <1>
mp.messaging.outgoing.prices.host=mqtt           # <2>
mp.messaging.outgoing.prices.port=1883           # <3>
----
1. Sets the connector for the `prices` channel
2. Configure the broker/server host name.
3. Configure the broker/server port. 1883 is the default.

NOTE: You don't need to set the MQTT topic. By default, it uses the channel name (`prices`). You can configure the `topic` attribute to override it.
NOTE: It is generally recommended to set the `client-id`. By default, the connector is generating a unique `client-id`.

Then, your application must send `Message<Double>` to the `prices` channel.
It can use `double` payloads as in the following snippet:

[source, java]
----
include::example$outbound/MqttPriceProducer.java[]
----

Or, you can send `Message<Double>`:

[source, java]
----
include::example$outbound/MqttPriceMessageProducer.java[]
----

=== Serialization

The `Message` sent to MQTT can have various payload types:

* https://vertx.io/docs/apidocs/io/vertx/core/json/JsonObject.html[`JsonObject`]: JSON string encoded as `byte[]`
* https://vertx.io/docs/apidocs/io/vertx/core/json/JsonArray.html[`JsonArray`]: JSON string encoded as `byte[]`
* `java.lang.String` and Java primitive types: `toString` encoded as `byte[]`
* `byte[]`
* complex objects: The objects are encoded to JSON and passed as `byte[]`


=== Outbound Metadata

The MQTT connector does not provide outbound metadata.

=== Configuration Reference

include::connectors:partial$META-INF/connector/smallrye-mqtt-outgoing.adoc[]

The MQTT connector is based on the https://vertx.io/docs/vertx-mqtt/java/#_vert_x_mqtt_client[Vert.x MQTT client].
So you can pass any attribute supported by this client.
