[#consuming-messages]
== Consuming Messages

To consume messages from a channel, you need to use the `@Incoming` annotation.
This annotation takes a single parameter: the name of the consumed channel.

Because `Messages` must be acknowledged, consuming messages requires returning _asynchronous results_ that would complete when the incoming message get acknowledged.

For example, you can receive the `Message`, process it and return the acknowledgement as result:

[source, java, indent=0]
----
include::example$consumption/ConsumptionExamples.java[tag=message-cs]
----

You can also return a `Uni` if you need to implement more complicated processing:

[source, java, indent=0]
----
include::example$consumption/ConsumptionExamples.java[tag=message-uni]
----

[#consuming-payloads]
== Consuming Payloads

Unlike consuming messages, consuming payloads support both synchronous and asynchronous consumption.

For example, you can consume a payload as follow:

[source, java, indent=0]
----
include::example$consumption/ConsumptionExamples.java[tag=payload-sync]
----

In this case, you don't need to deal with the acknowledgement yourself.
The framework acknowledges the incoming message (that wrapped the payload) once your method returns successfully.

If you need to achieve asynchronous actions, you can return a `CompletionStage` or a `Uni`:

[source, java, indent=0]
----
include::example$consumption/ConsumptionExamples.java[tag=payload-cs]
----

[source, java, indent=0]
----
include::example$consumption/ConsumptionExamples.java[tag=payload-uni]
----

In these 2 cases, the framework acknowledges the incoming message when the returned construct gets _completed_.
