
[#generating-payloads]
== Generating Payloads

Instead of `Message`, you can produce _payloads_.
In this case, Reactive Messaging produces a simple message from the _payload_ using `Message.of`.

=== Generating payload synchronously

You can produce _payloads_ synchronously.
The framework calls the method upon request and create `Messages` around the produced payloads.

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=payload-sync]
----

=== Generating payload using CompletionStage

You can also return `CompletionStage` or `CompletableFuture`.
For example, if you have an asynchronous client returning `CompletionStage`, you can use it as follows, to poll the data one by one:

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=payload-cs]
----

=== Generating payload by producing Unis

You can also return a `Uni` if you have a client using Mutiny types:

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=payload-uni]
----

=== Generating Reactive Streams of payloads

Finally, you can return a `Publisher` (or a sub-type):

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=payload-stream]
----

In this case, Reactive Messaging calls the method only once to retrieve the `Publisher`.
