[#generating-messages]
== Generating Messages

To produce messages to a channel, you need to use the `@Outgoing` annotation.
This annotation takes a single parameter: the name of the populated channel.

=== Generating messages synchronously

You can generate messages synchronously.
In this case, the method is called for every _request_ from the downstream:

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=message-sync]
----

[NOTE]
.Requests?
====
Reactive Messaging connects components to build a reactive stream.
In a reactive stream, the emissions are controlled by the consumer (downstream) indicating to the publisher (upstream) how many items it can consume.
With this protocol, the consumers are never flooded.
====

=== Generating messages using CompletionStage

You can also return a `CompletionStage` / `CompletableFuture`.
In this case, Reactive Messaging waits until the `CompletionStage` gets completed before calling it again.

For instance, this signature is useful to poll messages from a source using an asynchronous client:

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=message-cs]
----

=== Generating messages using Uni

You can also return a https://smallrye.io/smallrye-mutiny/#_uni_and_multi[Uni] instance.
In this case, Reactive Messaging waits until the `Uni` emits its item before calling it again.

This signature is useful when integrating asynchronous clients providing a Mutiny API.

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=message-uni]
----

=== Generating Reactive Streams of messages

Instead of producing the message one by one, you can return the stream directly.
If you have a data source producing Reactive Streams `Publisher` (or sub-types), this is the signature you are looking for:

[source, java, indent=0]
----
include::example$generation/GenerationExamples.java[tag=message-stream]
----

In this case, the method is called once to retrieve the `Publisher`.
