[#processing-messages]
== Processing Messages

You can process `Message` both synchronously or asynchronously.
This later case is useful when you need to execute an asynchronous action during your processing such as invoking a remote service.

Do process `Messages` synchronously uses:

[source, java, indent=0]
----
include::example$processing/ProcessingExamples.java[tag=process-message]
----

This method transforms the `int` payload to a `String`, and wraps it into a `Message`.

[IMPORTANT]
.Using `Message.withX` methods
====
You may be surprised by the usage of `Message.withX` methods.
It allows metadata propagation as the metadata would be copied from the incoming message and so dispatched to the next method.
====

You can also process `Messages` asynchronously:

[source, java, indent=0]
----
include::example$processing/ProcessingExamples.java[tag=process-message-cs]
----

Or using Mutiny:

[source, java, indent=0]
----
include::example$processing/ProcessingExamples.java[tag=process-message-uni]
----

In general, you want to create the new `Message` from the incoming one.
It enables metadata propagation and post-acknowledgement.
For this, use the `withX` method from the `Message` class returning a new `Message` instance but copy the _content_ (metadata, ack/nack...).

[#processing-payloads]
== Processing payloads

If you don't need to manipulate the envelope, you can process payload directly either synchronously or asynchronously:

[source, java, indent=0]
----
include::example$processing/ProcessingExamples.java[tag=process-payload]
----

[source, java, indent=0]
----
include::example$processing/ProcessingExamples.java[tag=process-payload-cs]
----

[source, java, indent=0]
----
include::example$processing/ProcessingExamples.java[tag=process-payload-uni]
----

[NOTE]
.What about metadata?
====
With these methods, the metadata are automatically propagated.
====


