= Sending / Receiving messages from non-reactive code

It is not rare to combine in a single application imperative parts (Jax-RS, regular CDI _beans_) and reactive parts (_beans_ with `@Incoming` and `@Outgoing` annotations).
In these case, it's often required to send _messages_ from the imperative part to the reactive part.
In other words, send messages to channels handled by reactive messaging and how can you retrieve messages.

== @Emitter and @Channel

To send _things_ (payload or `Message`) from imperative code to a specific channel you need to use:

1. the {javadoc-base}/org/eclipse/microprofile/reactive/messaging/Channel.html[`org.eclipse.microprofile.reactive.messaging.Channel`] annotations
2. the {javadoc-base}/org/eclipse/microprofile/reactive/messaging/Emitter.html[`org.eclipse.microprofile.reactive.messaging.Emitter`] type

The `@Channel` lets you indicate to which channel you are going to send your payloads or messages.
The `Emitter` is the object to use to send these payloads or messages.

[source, java, indent=0]
----
include::example$emitter/MyImperativeBean.java[tag=intro]
----

The `Emitter` class takes a type parameter. It's the type of payload.
Even if you want to send `Messages`, the type is the payload type.

IMPORTANT: You must have a `@Incoming("prices")` somewhere in your application (meaning a method consuming messages transiting on the channel `prices`), or an outbound connector configured to manage the `prices` channel (`mp.messaging.outgoing.prices...`)

[#emitter-payloads]
== Sending payloads

Sending payloads is done as follows:

[source, java, indent=0]
----
include::example$emitter/EmitterExamples.java[tag=payload]
----

When sending a payload, the emitter returns a `CompletionStage`.
This `CompletionStage` gets completed once the message created from the payload is acknowledged:

[source, java, indent=0]
----
include::example$emitter/EmitterExamples.java[tag=cs]
----

[#emitter-messages]
== Sending messages

You can also send `Messages`:

[source, java, indent=0]
----
include::example$emitter/EmitterExamples.java[tag=message]
----

When sending a `Message`, the emitter does not return a `CompletionStage`, but you can pass the acknowledgement callback, and be called when the message is acknowledged.

[source, java, indent=0]
----
include::example$emitter/EmitterExamples.java[tag=message-ack]
----

Sending messages also let you pass metadata.

[source, java, indent=0]
----
include::example$emitter/EmitterExamples.java[tag=message-meta]
----

Metadata can be used to propagate some context objects with the message.

[#emitter-overflow]
== Overflow management

When sending messages from imperative code to reactive code, you must be aware of back-pressure.
Indeed, messages sent using the emitter and stored in a _queue_.
If the consumer does not process the messages quickly enough, this queue can become a memory hog and you may even run out of memory.

To control what need to happen when the queue becomes out of control, use the {javadoc-base}/org/eclipse/microprofile/reactive/messaging/OnOverflow.Strategy.html[`org.eclipse.microprofile.reactive.messaging.OnOverflow`] annotation.
`@OnOverflow` lets you configure:

* the maximum size of the queue (default is 256)
* what need to happen when this size is reached (fail, drop...)

[source, java, indent=0]
----
include::example$emitter/EmitterExamples.java[tag=overflow]
----

The supported strategies are:

* `OnOverflow.Strategy.BUFFER` - use a buffer to store the elements until they are consumed. If
the buffer is full, a failure is propagated (and the thread using the emitted gets an exception)
* `OnOverflow.Strategy.UNBOUNDED_BUFFER` - use an unbounded buffer to store the elements
* `OnOverflow.Strategy.DROP` - drops the most recent value if the downstream can't keep up. It means that new value
emitted by the emitter are ignored.
* `OnOverflow.Strategy.FAIL` - propagates a failure in case the downstream can't keep up.
* `OnOverflow.Strategy.LATEST` - keeps only the latest value, dropping any previous value if the downstream can't keep up.
* `OnOverflow.Strategy.NONE` - ignore the back-pressure signals letting the downstream consumer to implement a strategy.

[#streams]
== Retrieving channels

You can use the `@Channel` annotation to inject in your bean the underlying stream.
Note that in this case, you will be responsible for the subscription:


[source, java, indent=0]
----
include::example$emitter/ChannelExamples.java[tag=channel]
----

IMPORTANT: You must have a `@Outgoing("my-channel")` somewhere in your application (meaning a method generating messages transiting on the channel `my-channel`), or an inbound connector configured to manage the `prices` channel (`mp.messaging.incoming.prices...`)

Be aware that when using a channel, the messages are not acknowledged automatically and, so, you must either handle the acknowledgment beforehand or manage it manually.


