== Advanced and Experimental features

=== @Merge

The `@Merge` annotation can be used on a method annotated with `@Incoming` to subscribed to all matching `@Outgoing
streams. For example, if you have several method producing data to a stream named "sink", the following method receives
all of them:

[source,java]
----
@Incoming("sink")
@Merge
@Acknowledgment(Acknowledgment.Mode.NONE)
public CompletionStage<Void> justASink(Message<String> ignored) {
  return CompletableFuture.completedFuture(null);
}
----

The `@Merge` annotation can be configured with a _merge policy_:

* `ONE` - Pick the first source and use only this one.
* `MERGE` - Merge the different sources. This strategy emits the items as they come. (default)
* `CONCAT` - Concat the sources.


=== @Broadcast

The `@Broadcast` annotation can be used on a method annotation with `@Outgoing` to broadcast the emitted messages to all
the matching subscribers:

[source, java]
----
@Outgoing("Y")
@Incoming("X")
@Broadcast
public String process(String s) {
  return s.toUpperCase();
}
----

=== @Stream

`@Stream` is a qualifier to inject a _stream_ into a regular CDI bean.
It's used to bridge the _imperative_ and _reactive_ worlds, or retrieve streams managed by Reactive Messaging.

You can retrieve a stream using:

[source,java]
----
@Inject
@Stream("hello")
private Publisher<Message<String>> field;
----

The value indicates the name of the stream. You can inject a stream as:

* `Publisher<Message<X>>` or `Publisher<X>`
* `PublisherBuilder<Message<X>>` or `PublisherBuilder<X>`
* `Flowable<Message<X>>` or `Flowable<X>`

You must have a `@Incoming("hello")` somewhere in your application (meaning a method consuming messages transiting on the stream `hello`),
 or a sink of message configured (`mp.messaging.outgoing.hello...`)

You can also emits data to a stream using:

[source, java]
----
@Inject @Stream("hello")
Emitter<String> emitter;

// ...
emitter.send("a").send("b");
----

You can inject an `io.smallrye.reactive.messaging.annotations.Emitter<T>` or `io.smallrye.reactive.messaging.annotations.Emitter<Message<T>>`.
To use an `Emitter` for the stream `hello`, you need a `@Incoming("hello")` somewhere in your code (or in your configuration).

=== Logging

The logging uses SLF4J, check the https://www.slf4j.org/[SLF4J web site] for further details.

=== Strict Binding Mode

By default, SmallRye Reactive Messaging does not enforce whether all _mediators_ are connected. It just print a warning
message. The strict mode fails the deployment if some "incoming" are not connected to "outgoing". To enable this mode,
pass the `-Dsmallrye-messaging-strict-binding=true` to the command line.
