== Advanced and Experimental features

=== @Merge

The `@Merge` annotation can be used on a method annotated with `@Incoming` to subscribed to all matching `@Outgoing
channels. For example, if you have several method producing data to a channel named "sink", the following method receives
all of them:

[source,java]
----
@Incoming("sink")
@Merge
@Acknowledgment(Acknowledgment.Mode.NONE)
public CompletionStage<Void> justASink(Message<String> ignored) {
  return CompletableFuture.completedFuture(null);
}
----

The `@Merge` annotation can be configured with a _merge policy_:

* `ONE` - Pick the first source and use only this one.
* `MERGE` - Merge the different sources. This strategy emits the items as they come. (default)
* `CONCAT` - Concat the sources.


=== @Broadcast

The `@Broadcast` annotation can be used on a method annotation with `@Outgoing` to broadcast the emitted messages to all
the matching subscribers:

[source, java]
----
@Outgoing("Y")
@Incoming("X")
@Broadcast
public String process(String s) {
  return s.toUpperCase();
}
----

=== @Channel

`@Channel` is a qualifier to inject a _channel_ into a regular CDI bean.
It's used to bridge the _imperative_ and _reactive_ worlds, or retrieve channels managed by Reactive Messaging.

You can retrieve a channel using:

[source,java]
----
@Inject
@Channel("hello")
private Publisher<Message<String>> field;
----

The value indicates the name of the channel. You can inject a channel as:

* `Publisher<Message<X>>` or `Publisher<X>`
* `PublisherBuilder<Message<X>>` or `PublisherBuilder<X>`
* `Flowable<Message<X>>` or `Flowable<X>`

You must have a `@Incoming("hello")` somewhere in your application (meaning a method consuming messages transiting on the channel `hello`),
 or a sink of message configured (`mp.messaging.outgoing.hello...`)

You can also emits data to a channel using:

[source, java]
----
@Inject @Channel("hello")
Emitter<String> emitter;

// ...
emitter.send("a").send("b");
----

You can inject an `io.smallrye.reactive.messaging.Emitter<T>`.
To use an `Emitter` for the channel `hello`, you need a `@Incoming("hello")` somewhere in your code (or in your configuration).

When injecting an `Emitter` you can configure how the back-pressure is handled.
The `OnOverflow` annotation configures what needs to happen when you emit payloads/messages faster than the downstream can consumes.
By default a buffer of 127 items is used to manage _bumps_.
You can change this behavior as follows:

[source, java]
----
@Inject
@Channel("hello")
@OnOverflow(value = OnOverflow.Strategy.BUFFER, bufferSize = 300)
Emitter<String> emitter;

// ...
emitter.send("a").send("b");
----

In this snippet, the buffer size is set to `300`. If you omit the `bufferSize` (in conjunction with the `BUFFER` strategy) an unbounded buffer is used.
The `value` attribute can be:

* `OnOverflow.Strategy.BUFFER` - use a buffer, potentially unbounded to store the elements until they are consumed. If
the buffer is full, a failure is propagated (and the thread using the emitted gets an exception)
* `OnOverflow.Strategy.DROP` - drops the most recent value if the downstream can't keep up. It means that new value
emitted by the emitter are ignored.
* `OnOverflow.Strategy.FAIL` - propagates a failure in case the downstream can't keep up.
* `OnOverflow.Strategy.LATEST` - keeps only the latest value, dropping any previous value if the downstream can't keep up.
* `OnOverflow.Strategy.NONE` - ignore the back-pressure signals letting the downstream consumer to implement a strategy.

Here are some examples:

[source, java]
----
@Inject
@Channel("hello") // Buffer strategy using the default buffer size
Emitter<String> emitter;

@Inject
@Channel("hello")
@OnOverflow(value = OnOverflow.Strategy.BUFFER) // Buffer strategy, unbounded buffer
Emitter<String> emitter;

@Inject
@Channel("hello")
@OnOverflow(value = OnOverflow.Strategy.DROP) // Drop the most recent values
Emitter<String> emitter;
----

The default buffer size (`127`) can be configured using the `smallrye.messaging.emitter.default-buffer-size` property set using MicroProfile Config.
Note that this value is only applied when `OnOverflow` is not used.

An emitter can also send messages directly:

[source, java]
----
@Inject
@Channel("hello")
Emitter<String> emitter;

// ...
emitter.send(Message.of("hello"));
----

When sending a payload, the `send` method returns a `CompletionStage<Void>` completed when the message is acknowledged:

[source, java]
----
@Inject
@Channel("hello")
Emitter<String> emitter;

// ...
CompletionStage<Void> cs = emitter.send("hello");
----

=== Logging

The logging uses SLF4J, check the https://www.slf4j.org/[SLF4J web site] for further details.

=== Strict Binding Mode

By default, SmallRye Reactive Messaging does not enforce whether all _mediators_ are connected. It just print a warning
message. The strict mode fails the deployment if some "incoming" are not connected to "outgoing". To enable this mode,
pass the `-Dsmallrye-messaging-strict-binding=true` to the command line.
