== Receiving and Sending AMQP 1.0 Messages

You can connect to an AMQP broker or server as a source or sink.
The AMQP support is based on the https://vertx.io/docs/vertx-amqp-client/java/[Vert.x AMQP Client].

=== Dependency

To enable the AMQP support, you need the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-amqp</artifactId>
  <version>{version}</version>
</dependency>
----

=== Receiving messages from AMQP

[source]
----
mp.messaging.incoming.data.address=data
mp.messaging.incoming.data.connector=smallrye-amqp
mp.messaging.incoming.data.host=localhost
mp.messaging.incoming.data.port=5672
mp.messaging.incoming.data.username=username
mp.messaging.incoming.data.password=secret
mp.messaging.incoming.data.broadcast=true
mp.messaging.incoming.data.containerId=my-container-id
----

As the AMQP support is based on the Vert.x AMQP client, you can pass any configuration supported by the client.
Check the  https://vertx.io/docs/vertx-amqp-client/java/[documentation] of the client for further details.

NOTE: If the `address` attribute is not set the channel name is used instead.

The payload must be a supported AMQP type.
These metadata can be retrieved using the `io.smallrye.reactive.messaging.amqp.IncomingAmqpMetadata` class:

[source, java]
----
IncomingAmqpMetadata metadata = message.getMetadata(IncomingAmqpMetadata.class);
String address = metadata.getAddress();
int priority = metadata.getPriority();
----

=== Sending messages to AMQP

[source]
----
mp.messaging.outgoing.data.address=data
mp.messaging.outgoing.data.connector=smallrye-amqp
mp.messaging.outgoing.data.host=localhost
mp.messaging.outgoing.data.port=5672
mp.messaging.outgoing.data.username=username
mp.messaging.outgoing.data.password=secret
mp.messaging.outgoing.data.containerId=my-container-id
mp.messaging.outgoing.data.durable=true
----

The AMQP connector dispatches messages to the AMQP broker or server.

The payload of the message must be one of the following type:

* String
* Boolean, Byte, Character, Double, Float, Integer, Long, Short
* Buffer
* Instant
* (Vert.x) JSON Array or JSON Object (send as binary with content type set to `application/json`)
* UUID

Otherwise, the connector invokes `toString` on the wrapped payload.

NOTE: If the `address` attribute is not set the channel name is used instead.
If the AMQP Message has an address set, this address is used.

Instead of an `AMQPMessage` you can attach an instance of `io.smallrye.reactive.messaging.amqp.OutgoingAmqpMessage` as metadata:

[source, java]
----
Message<String> incoming = ...;
OutgoingAmqpMessage amqp = OutgoingAmqpMessage.builder()
    .setAddress("some-adress")
    .build();
Message<String> outgoing = incoming.withMetadata(incoming.getMetadata().with(amqp));
----

=== Global configuration

The host, port, username, password, SSL connection, reconnect attempts, reconnect interval,
and connection timeout can also be configured using the `amqp-host`, `amqp-port`, `amqp-username`,
`amqp-password`, `amqp-use-ssl`, `amqp-reconnect-attempts`, `amqp-reconnect-interval`, and
`amqp-connect-timeout` configuration properties.

Also there is the possibility to provide a named bean AmqpClientOptions to configure the details to connect with the remote broker.

[source]
----
mp.messaging.incoming.data.address=data
mp.messaging.incoming.data.connector=smallrye-amqp
mp.messaging.incoming.data.broadcast=true
mp.messaging.incoming.data.client-options-name=custom-client-config
----
[source]
----
    @Produces
    @Named("custom-client-config")
    public AmqpClientOptions amqpClientConfig() {
        return new AmqpClientOptions()
                .setHost("localhost")
                .setPort(5672)
                .setUsername("username")
                .setPassword("secret")
                .setContainerId("my-container-id");
    }
----
