== Interacting using AMQP

You can connect to an AMQP broker or server as a source or sink.
The AMQP support is based on the https://vertx.io/docs/vertx-amqp-client/java/[Vert.x AMQP Client].

=== Dependency

To enable the AMQP support, you need the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-amqp-1.0</artifactId>
  <version>{version}</version>
</dependency>
----

=== Retrieving messages from AMQP

[source]
----
mp.messaging.incoming.data.address=data
mp.messaging.incoming.data.connector=smallrye-amqp
mp.messaging.incoming.data.host=localhost
mp.messaging.incoming.data.port=5672
mp.messaging.incoming.data.username=username
mp.messaging.incoming.data.password=secret
mp.messaging.incoming.data.broadcast=true
mp.messaging.incoming.data.containerId=my-container-id
----

Message coming from AMQP are `io.smallrye.reactive.messaging.amqp.AmqpMessage`.
The payload must a a supported AMQP type.
The `AmqpMessage` implements `Message` and provide additional metadata related to AMQP.

As the AMQP support is based on the Vert.x AMQP client, you can pass any configuration supported by the client.
Check the  https://vertx.io/docs/vertx-amqp-client/java/[documentation] of the client for further details.

NOTE: If the `address` attribute is not set the channel name is used instead.

=== Forwarding messages to AMQP

[source]
----
mp.messaging.outgoing.data.address=data
mp.messaging.incoming.data.connector=smallrye-amqp
mp.messaging.outgoing.data.host=localhost
mp.messaging.outgoing.data.port=5672
mp.messaging.outgoing.data.username=username
mp.messaging.outgoing.data.password=secret
mp.messaging.outgoing.data.containerId=my-container-id
mp.messaging.outgoing.data.durable=true
mp.messaging.outgoing.data.durable=10000
----

The AMQP connector dispatches messages to the AMQP broker or server.
You can send _bare_ message or `io.smallrye.reactive.messaging.amqp.AmqpMessage`.

The payload of the message must be one of the following type:

* String
* Boolean, Byte, Character, Double, Float, Integer, Long, Short
* Buffer
* Instant
* (Vert.x) JSON Array or JSON Object (send as binary with content type set to `application/json`)
* UUID

Otherwise, the connector invokes `toString` on the wrapped payload.

NOTE: If the `address` attribute is not set the channel name is used instead.

The host, port, username and password can also be configured using the `amqp-host`, `amqp-port`, `amqp-username` and `amqp-password` configuration properties.

