== Integrating with Apache Camel

You can receive messages from a Camel Route or send messages to a Camel route. It give you the ability to connect to
almost any existing system.

=== Dependency

To enable the Camel support, you need the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-camel</artifactId>
  <version>{version}</version>
</dependency>
----

=== Camel Reactive

When using the dependency, your bean can retrieve a
 `org.apache.camel.component.reactive.streams.api.CamelReactiveStreamsService` object:

[source,java]
----
// Default Camel Context
@Inject
private CamelContext camel;

// Camel Reactive service
@Inject
private CamelReactiveStreamsService camel_reactive;
----

=== Using Camel Route in @Outgoing method

Here is an example of method annotated with `@Outgoing` directly using a Camel route:

[source, java]
----
@Outgoing("camel")
public Publisher<Exchange> source() {
  return camel_reactive.from("seda:camel");
}
----

=== Using Camel Route in @Incoming method

Here is an example of method annotated with `@Incoming` directly using a Camel route:

[source, java]
----
@Incoming("camel")
public Subscriber<String> sink() {
  return camel.subscriber("file:./target?fileName=values.txt&fileExist=append", String.class);
}
----

Another possibility is to use a _producer_:

[source,java]
----
@Incoming("camel")
public CompletionStage<Void> sink(String value) {
  return camel.createProducerTemplate().asyncSendBody("file:./target?fileName=values.txt&fileExist=append", value).thenApply(x -> null);
}
----


=== Retrieving messages from a Camel Route

The previous example requires your code to deal with Maven route directly. It can be externalized to the configuration as
follows:

[source]
----
mp.messaging.incoming.data.connector=smallrye-camel
mp.messaging.incoming.data.endpoint-uri:seda:my-route
----

The `endpoint-uri` configures the route to use. It can be:

1. a `reactive-stream` route such as `reactive-streams:out`
2. a _regular_ route such as `seda:my-route`

=== Forwarding messages to a Camel Route

The following configuration describe a sink using a Camel route:

[source]
----
mp.messaging.outgoing.data.connector=smallrye-camel
mp.messaging.outgoing.data.endpoint-uri:seda:my-route
----

The `endpoint-uri` configures the route to use. It can be:

1. a `reactive-stream` route such as `reactive-streams:in`
2. a _regular_ route such as `file:./target?fileName=values.txt&fileExist=append`

In the first case, it can be used as follows:

[source,java]
----
@ApplicationScoped
public class BeanWithCamelSinkUsingRSRoute extends RouteBuilder {

  @Outgoing("data")
  public Publisher<Message<String>> source() {
    return ReactiveStreams.of("a", "b", "c", "d")
      .map(String::toUpperCase)
      .map(Message::of)
      .buildRs();
  }

  // Declare a route
  @Override
  public void configure() {
    from("reactive-streams:in").to("file:./target?fileName=values.txt&fileExist=append");
  }
}
----

