== Interacting with Apache Kafka

You can connect to Apache Kafka as a source or sink. The Kafka support is based on the
https://vertx.io/docs/vertx-kafka-client/java/[Vert.x Kafka Client].

=== Dependency

To enable the Kafka support, you need the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-kafka-1.0</artifactId>
  <version>{version}</version>
</dependency>
----

=== Retrieving messages from Kafka

To retrieve messages from a Kafka topic, you need the following configuration:

[source]
----
# [Source - heartbeat] - Consume data from Kafka
mp.messaging.incoming.kafka-heartbeat.connector=smallrye-kafka
mp.messaging.incoming.kafka-heartbeat.topic=heartbeat
mp.messaging.incoming.kafka-heartbeat.bootstrap.servers=localhost:9092
mp.messaging.incoming.kafka-heartbeat.group.id=demo
mp.messaging.incoming.kafka-heartbeat.value.deserializer=io.vertx.kafka.client.serialization.JsonObjectDeserializer
# [/Source - heartbeat]
----

The `connector` attribute is required to indicate you are configuring the Kafka transport. Supported attributes are listed
in the following table:

|===

| Attribute | Mandatory | Default | Description

| topic | true | the `channel-name` | The topic to consume, use the `channel-name` if not set
| bootstrap.servers | false | `localhost:9092` | the comma separated list of servers (host:port), Can also
be set using the `kafka.bootstrap.servers` config property.
| key.deserializer | false | | the codec used to deserialize the key, `String` by default
| value.deserializer | true | | the codec used to deserialize the value
| group.id | false (BUT should be set in production)  | | the group id. A new random group id is generated if omitted. This feature is only for development. In production, a group id should be set.
| enable.auto.commit | false | false | whether or not the messages are committed automatically
| retry | false | true | Whether it should retry to re-established the connection to the broker is it fails
| retry-attempts | false | 5 | Number of retries
| broadcast | false | false | Whether the received messages can be dispatched to several `@Incoming`
|===

You can also configure any attributes used by the https://vertx.io/docs/vertx-kafka-client/java/[Vert.x Kafka client].

When consuming a message from Kafka, you can get the `Message` as a `io.smallrye.reactive.messaging.kafka.KafkaMessage`.
It lets you access other metadata such as the headers, the message key (the payload being the value):

[source,java]
----
include::../examples/snippets/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConsumer.java[tag=kafka-message]
----


=== Forwarding messages to Kafka

To send messages to a Kafka topic, you need the following configuration:

[source]
----
# [Sink - data] - Produce data to Kafka
mp.messaging.outgoing.data.connector=smallrye-kafka
mp.messaging.outgoing.data.value.serializer=io.vertx.kafka.client.serialization.JsonObjectSerializer
# [/Sink - data]
----

The `connector` attribute is required to indicate you are configuring the Kafka transport. Supported attributes are listed
in the following table:

|===

| Attribute | Mandatory | Default | Description

| topic | false | the `channel-name` | The topic to consume, if not set it must be set in the `message`
| bootstrap.servers | false | `localhost:9092` | the comma separated list of servers (host:port), Can also
be set using the `kafka.bootstrap.servers` config property.
| key.serializer | false | `String` | the codec used to serialize the key, `String` if not set
| value.serializer | true | | the codec used to serialize the value
| key | false | | the key to be used, can be overridden by the message
| partition | false | none | the partition
| waitForWriteCompletion | false | `false` | whether it needs to wait for the _write_ operation to complete before processing the next message
|===

You can also configure any attributes used by the https://vertx.io/docs/vertx-kafka-client/java/[Vert.x Kafka client].

When sending a message to Kafka, you can send a Kafka message to configure various aspects such as the topic and key:

[source,java]
----
include::../examples/snippets/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaProducer.java[tag=kafka-message]
----
