== Connecting transports

SmallRye Reactive Messaging supports various transport _protocols_.
This section explains how you can configure these different _connectors_.
Before listing the supported transports, we need to explain the configuration format.
SmallRye Reactive Messaging uses MicroProfile Config as main configuration source.
To enable the configuration, add an implementation of MicroProfile Config in your _classpath_.
For instance, add the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye</groupId>
  <artifactId>smallrye-config-1.3</artifactId>
  <version>{smallrye-config-version}</version>
</dependency>
----

Then create a _properties_ file in `src/main/resources/META-INF/microprofile-config.properties` such as:

[source]
----
# Configure two channels using a dummy connector
mp.messaging.incoming.dummy-incoming-channel.connector=dummy
mp.messaging.incoming.dummy-incoming-channel.attribute=value
mp.messaging.outgoing.dummy-outgoing-channel.connector=dummy
mp.messaging.outgoing.dummy-incoming-channel.attribute=value
----

Each channel (both incoming and outgoing) are configured individually in this file:

* an `incoming` channel consumes data from a message broker or something producing data.
 It can be connected to a method annotated with an `@Incoming` using the same channel name.
* an `outgoing` consumes data from the application and forward it to a message broker or something consuming data.
 It can be connected to a method annotated with an `@Outgoing` using the same channel name.

The configuration format is the follow:

[source]
----
mp.messaging.[outgoing|incoming].[channel-name].[attribute]=[value]
----
1. the `[outgoing|incoming]` segment indicates the direction of the channel
2. the `[channel-name]` segment configures the name of the channel
3. the `[attribute]` segment is the name of the attribute to configure.
Most of the time the attributes are specific to the transport layer
4. the `[value]` is the value

All `channels` must declare the `connector` attribute matching the name of the connector.

Here is an example of a channel using a MQTT connector, consuming data from a MQTT broker, and a channel using a Kafka connector (forwarding data to Kafka):

[source]
----
# [Channel - health] - Consume data from MQTT
mp.messaging.incoming.health.topic=neo
mp.messaging.incoming.health.connector=smallrye-mqtt
mp.messaging.incoming.health.host=localhost
mp.messaging.incoming.health.broadcast=true
# [/Channel - health]

# [Channel - data] - Produce data to Kafka
mp.messaging.outgoing.data.connector=smallrye-kafka
mp.messaging.outgoing.data.bootstrap.servers=localhost:9092
mp.messaging.outgoing.data.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.data.value.serializer=io.vertx.kafka.client.serialization.JsonObjectSerializer
mp.messaging.outgoing.data.acks=1
# [/Channel - data]
----



