package io.smallrye.reactive.messaging.mqtt;

import java.util.concurrent.TimeUnit;

import io.vertx.mqtt.MqttClientOptions;

public class MqttHelpers {

    private MqttHelpers() {
        // avoid direct instantiation.
    }

    static MqttClientOptions createMqttClientOptions(MqttConnectorCommonConfiguration config) {
        MqttClientOptions options = new MqttClientOptions();
        options.setClientId(config.getClientId().orElse(null));
        options.setAutoGeneratedClientId(config.getAutoGeneratedClientId());
        options.setAutoKeepAlive(config.getAutoKeepAlive());
        options.setSsl(config.getSsl());
        options.setWillQoS(config.getWillQos());
        options.setWillFlag(config.getWillFlag());
        options.setWillRetain(config.getWillRetain());
        options.setKeepAliveTimeSeconds(config.getKeepAliveSeconds());
        options.setMaxInflightQueue(config.getMaxInflightQueue());
        options.setCleanSession(config.getAutoCleanSession());
        options.setMaxInflightQueue(config.getMaxInflightQueue());
        options.setReconnectAttempts(config.getReconnectAttempts());
        options.setReconnectInterval(TimeUnit.SECONDS.toMillis(config.getReconnectIntervalSeconds()));
        options.setUsername(config.getUsername().orElse(null));
        options.setPassword(config.getPassword().orElse(null));
        options.setConnectTimeout((int) TimeUnit.SECONDS.toMillis(config.getConnectTimeoutSeconds()));
        options.setTrustAll(config.getTrustAll());
        return options;
    }
}
