package io.smallrye.reactive.messaging.mqtt.session.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import java.time.Duration;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.TimeUnit;

import org.eclipse.microprofile.config.ConfigProvider;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

import io.netty.handler.codec.mqtt.MqttQoS;
import io.smallrye.config.SmallRyeConfigProviderResolver;
import io.smallrye.reactive.messaging.mqtt.MqttTestBase;
import io.smallrye.reactive.messaging.mqtt.session.ConstantReconnectDelayOptions;
import io.smallrye.reactive.messaging.mqtt.session.MqttClientSession;
import io.smallrye.reactive.messaging.mqtt.session.MqttClientSessionOptions;
import io.smallrye.reactive.messaging.mqtt.session.RequestedQoS;
import io.smallrye.reactive.messaging.mqtt.session.SessionEvent;
import io.smallrye.reactive.messaging.mqtt.session.SessionState;
import io.smallrye.reactive.messaging.mqtt.session.SubscriptionEvent;
import io.smallrye.reactive.messaging.mqtt.session.SubscriptionState;
import io.vertx.core.buffer.Buffer;
import io.vertx.mutiny.core.Vertx;

class MqttClientSessionImplTest {

    static GenericContainer<?> mosquitto = new GenericContainer<>("eclipse-mosquitto:2.0")
            .withExposedPorts(1883)
            .withCopyFileToContainer(MountableFile.forClasspathResource("mosquitto.conf"), "/mosquitto/config/mosquitto.conf")
            .waitingFor(Wait.forListeningPort())
            .waitingFor(Wait.forLogMessage(".*mosquitto .* running.*", 1));

    private Vertx vertx;
    private String host;
    private int port;

    @BeforeAll
    static void startBroker() {
        mosquitto.start();
        MqttTestBase.awaitForMosquittoToBeReady(mosquitto);
    }

    @AfterAll
    static void stopBroker() {
        mosquitto.stop();
    }

    @BeforeEach
    void setup() {
        vertx = Vertx.vertx();
        host = mosquitto.getHost();
        port = mosquitto.getMappedPort(1883);
    }

    @AfterEach
    void tearDown() {
        System.clearProperty("mqtt-host");
        System.clearProperty("mqtt-port");
        System.clearProperty("mqtt-user");
        System.clearProperty("mqtt-pwd");
        vertx.closeAndAwait();

        SmallRyeConfigProviderResolver.instance().releaseConfig(ConfigProvider.getConfig());
    }

    private MqttClientSessionOptions defaultOptions() {
        MqttClientSessionOptions options = new MqttClientSessionOptions();
        options.setHostname(host);
        options.setPort(port);
        options.setAutoGeneratedClientId(true);
        ConstantReconnectDelayOptions reconnect = new ConstantReconnectDelayOptions();
        reconnect.setDelay(Duration.ofSeconds(1));
        options.setReconnectDelay(reconnect);
        return options;
    }

    @Test
    void lifecycleDisconnectedToConnected() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<SessionState> states = new CopyOnWriteArrayList<>();
        session.sessionStateHandler(e -> states.add(e.getSessionState()));

        assertThat(session.getState()).isEqualTo(SessionState.DISCONNECTED);

        session.start();

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        assertThat(states).contains(SessionState.CONNECTING, SessionState.CONNECTED);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);

        assertThat(states).contains(SessionState.DISCONNECTING, SessionState.DISCONNECTED);
    }

    @Test
    void startTwiceIsNoOp() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        // Second start should succeed immediately since already connected
        session.start().toCompletionStage().toCompletableFuture().get(5, TimeUnit.SECONDS);
        assertThat(session.getState()).isEqualTo(SessionState.CONNECTED);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void stopTwiceIsNoOp() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);

        // Second stop should succeed immediately since already disconnected
        session.stop().toCompletionStage().toCompletableFuture().get(5, TimeUnit.SECONDS);
        assertThat(session.getState()).isEqualTo(SessionState.DISCONNECTED);
    }

    @Test
    void subscribeAndReceiveMessages() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<String> receivedMessages = new CopyOnWriteArrayList<>();

        session.messageHandler(msg -> receivedMessages.add(msg.payload().toString()));

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/session/" + System.currentTimeMillis();
        session.subscribe(topic, RequestedQoS.QOS_0)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getSubscriptionState(topic) == SubscriptionState.SUBSCRIBED);

        // Publish a message using the same session
        session.publish(topic, Buffer.buffer("hello"), MqttQoS.AT_MOST_ONCE)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> receivedMessages.size() >= 1);
        assertThat(receivedMessages).contains("hello");

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void duplicateSubscribeReturnsSameQoS() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/dup/" + System.currentTimeMillis();
        Integer qos1 = session.subscribe(topic, RequestedQoS.QOS_1)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        // Second subscribe to same topic should return the existing QoS without re-subscribing
        Integer qos2 = session.subscribe(topic, RequestedQoS.QOS_0)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        // Should return the originally requested QoS (1)
        assertThat(qos2).isEqualTo(RequestedQoS.QOS_1.toInteger());

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void subscribeUnsubscribeStateTransitions() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<SubscriptionEvent> events = new CopyOnWriteArrayList<>();
        session.subscriptionStateHandler(events::add);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/unsub/" + System.currentTimeMillis();
        session.subscribe(topic, RequestedQoS.QOS_0)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getSubscriptionState(topic) == SubscriptionState.SUBSCRIBED);

        session.unsubscribe(topic);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getSubscriptionState(topic) == SubscriptionState.UNSUBSCRIBED);

        // Verify state transitions: SUBSCRIBING -> SUBSCRIBED -> UNSUBSCRIBED
        assertThat(events.stream().map(SubscriptionEvent::getSubscriptionState))
                .containsSubsequence(SubscriptionState.SUBSCRIBING, SubscriptionState.SUBSCRIBED,
                        SubscriptionState.UNSUBSCRIBED);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void publishWhenDisconnectedFails() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());

        // Don't start the session - it remains disconnected
        assertThat(session.getState()).isEqualTo(SessionState.DISCONNECTED);

        try {
            session.publish("test/topic", Buffer.buffer("data"), MqttQoS.AT_MOST_ONCE)
                    .toCompletionStage().toCompletableFuture().get(5, TimeUnit.SECONDS);
            assertThat(true).as("Expected exception").isFalse();
        } catch (Exception e) {
            assertThat(e.getCause()).hasMessageContaining("Session is not connected");
        }
    }

    @Test
    void sessionStateHandlerCalledOnEachTransition() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<SessionState> states = new CopyOnWriteArrayList<>();
        session.sessionStateHandler(e -> states.add(e.getSessionState()));

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);

        assertThat(states).containsSubsequence(
                SessionState.CONNECTING,
                SessionState.CONNECTED,
                SessionState.DISCONNECTING,
                SessionState.DISCONNECTED);
    }

    @Test
    void subscriptionStateHandlerCalledOnSubscribe() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<SubscriptionEvent> events = new CopyOnWriteArrayList<>();
        session.subscriptionStateHandler(events::add);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/sub-handler/" + System.currentTimeMillis();
        session.subscribe(topic, RequestedQoS.QOS_1)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> events.stream()
                        .anyMatch(e -> e.getSubscriptionState() == SubscriptionState.SUBSCRIBED));

        assertThat(events).anyMatch(e -> e.getTopic().equals(topic)
                && e.getSubscriptionState() == SubscriptionState.SUBSCRIBING);
        assertThat(events).anyMatch(e -> e.getTopic().equals(topic)
                && e.getSubscriptionState() == SubscriptionState.SUBSCRIBED
                && e.getQos() != null);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void publishCompletionHandlerCalledForQoS1() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<Integer> completedIds = new CopyOnWriteArrayList<>();
        session.publishCompletionHandler(completedIds::add);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/pubcomp/" + System.currentTimeMillis();
        Integer packetId = session.publish(topic, Buffer.buffer("qos1-msg"), MqttQoS.AT_LEAST_ONCE, false, false)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> completedIds.contains(packetId));

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void exceptionHandlerInvoked() throws Exception {
        // Use an invalid host to trigger a connection error
        MqttClientSessionOptions options = new MqttClientSessionOptions();
        options.setHostname("invalid.host.that.does.not.exist.example.com");
        options.setPort(1883);
        options.setAutoGeneratedClientId(true);
        options.setConnectTimeout(2000);
        ConstantReconnectDelayOptions reconnect = new ConstantReconnectDelayOptions();
        reconnect.setDelay(Duration.ofHours(1)); // Long delay so we don't get repeated reconnects
        options.setReconnectDelay(reconnect);

        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);
        List<SessionState> states = new CopyOnWriteArrayList<>();
        session.sessionStateHandler(e -> states.add(e.getSessionState()));

        session.start();

        // Should eventually reach DISCONNECTED due to connection failure
        await().atMost(30, TimeUnit.SECONDS)
                .until(() -> states.contains(SessionState.DISCONNECTED));

        session.stop();
    }

    @Test
    void isConnectedReturnsCorrectValue() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());

        assertThat(session.isConnected()).isFalse();

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(session::isConnected);

        assertThat(session.isConnected()).isTrue();

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> !session.isConnected());

        assertThat(session.isConnected()).isFalse();
    }

    @Test
    void subscriptionsResetOnDisconnect() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        List<SubscriptionEvent> events = new CopyOnWriteArrayList<>();
        session.subscriptionStateHandler(events::add);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/reset/" + System.currentTimeMillis();
        session.subscribe(topic, RequestedQoS.QOS_0)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getSubscriptionState(topic) == SubscriptionState.SUBSCRIBED);

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);

        // On disconnect, all subscriptions should be set to UNSUBSCRIBED
        assertThat(events.stream()
                .filter(e -> e.getSubscriptionState() == SubscriptionState.UNSUBSCRIBED)
                .map(SubscriptionEvent::getTopic))
                .contains(topic);
    }

    @Test
    void publishQoS0Succeeds() throws Exception {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/qos0/" + System.currentTimeMillis();
        Integer packetId = session.publish(topic, Buffer.buffer("qos0"), MqttQoS.AT_MOST_ONCE, false, false)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        // Publish should succeed and return a packet ID
        assertThat(packetId).isNotNull();

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void getSubscriptionStateForUnknownTopicReturnsNull() {
        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), defaultOptions());
        assertThat(session.getSubscriptionState("unknown/topic")).isNull();
    }

    @Test
    void sessionEventContainsCauseOnError() throws Exception {
        MqttClientSessionOptions options = new MqttClientSessionOptions();
        options.setHostname("invalid.host.that.does.not.exist.example.com");
        options.setPort(1883);
        options.setAutoGeneratedClientId(true);
        options.setConnectTimeout(2000);
        ConstantReconnectDelayOptions reconnect = new ConstantReconnectDelayOptions();
        reconnect.setDelay(Duration.ofHours(1));
        options.setReconnectDelay(reconnect);

        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);
        List<SessionEvent> events = new CopyOnWriteArrayList<>();
        session.sessionStateHandler(events::add);

        session.start();

        await().atMost(30, TimeUnit.SECONDS)
                .until(() -> events.stream()
                        .anyMatch(e -> e.getSessionState() == SessionState.DISCONNECTED));

        // The DISCONNECTED event should have a cause
        SessionEvent disconnectedEvent = events.stream()
                .filter(e -> e.getSessionState() == SessionState.DISCONNECTED)
                .findFirst()
                .orElseThrow();
        assertThat(disconnectedEvent.getCause()).isNotNull();

        session.stop();
    }

    @Test
    void publishQoS1RetriesOnInflightQueueFull() throws Exception {
        MqttClientSessionOptions options = defaultOptions();
        options.setMaxInflightQueue(1);
        options.setPublishMaxRetries(3);

        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/retry-inflight/" + System.currentTimeMillis();

        // Send two QoS 1 messages rapidly — the second hits inflight queue full
        // and should be retried after the first's PUBACK frees the slot
        var f1 = session.publish(topic, Buffer.buffer("msg1"), MqttQoS.AT_LEAST_ONCE, false, false)
                .toCompletionStage().toCompletableFuture();
        var f2 = session.publish(topic, Buffer.buffer("msg2"), MqttQoS.AT_LEAST_ONCE, false, false)
                .toCompletionStage().toCompletableFuture();

        Integer id1 = f1.get(10, TimeUnit.SECONDS);
        Integer id2 = f2.get(10, TimeUnit.SECONDS);
        assertThat(id1).isNotNull();
        assertThat(id2).isNotNull();

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void publishQoS1FailsWhenRetriesDisabled() throws Exception {
        MqttClientSessionOptions options = defaultOptions();
        options.setMaxInflightQueue(1);
        options.setPublishMaxRetries(0);

        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/no-retry/" + System.currentTimeMillis();

        // Send two QoS 1 messages rapidly — the second should fail immediately
        var f1 = session.publish(topic, Buffer.buffer("msg1"), MqttQoS.AT_LEAST_ONCE, false, false)
                .toCompletionStage().toCompletableFuture();
        var f2 = session.publish(topic, Buffer.buffer("msg2"), MqttQoS.AT_LEAST_ONCE, false, false)
                .toCompletionStage().toCompletableFuture();

        assertThat(f1.get(10, TimeUnit.SECONDS)).isNotNull();

        try {
            f2.get(10, TimeUnit.SECONDS);
            assertThat(true).as("Expected exception for inflight queue full").isFalse();
        } catch (Exception e) {
            assertThat(e.getCause()).isNotNull();
        }

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void publishMultipleQoS1WithRetryOnInflightQueueFull() throws Exception {
        MqttClientSessionOptions options = defaultOptions();
        options.setMaxInflightQueue(1);
        options.setPublishMaxRetries(5);

        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);
        List<String> receivedMessages = new CopyOnWriteArrayList<>();

        session.messageHandler(msg -> receivedMessages.add(msg.payload().toString()));

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/retry-multi/" + System.currentTimeMillis();
        session.subscribe(topic, RequestedQoS.QOS_1)
                .toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);

        // Send 5 messages rapidly with maxInflight=1 — most will need retries
        var futures = new java.util.ArrayList<java.util.concurrent.CompletableFuture<Integer>>();
        for (int i = 0; i < 5; i++) {
            futures.add(session.publish(topic, Buffer.buffer("msg" + i), MqttQoS.AT_LEAST_ONCE, false, false)
                    .toCompletionStage().toCompletableFuture());
        }

        // All should eventually succeed
        for (var f : futures) {
            assertThat(f.get(30, TimeUnit.SECONDS)).isNotNull();
        }

        // Verify all messages were received
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> receivedMessages.size() >= 5);
        assertThat(receivedMessages).containsExactlyInAnyOrder("msg0", "msg1", "msg2", "msg3", "msg4");

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void publishQoS2WithRetryOnInflightQueueFull() throws Exception {
        MqttClientSessionOptions options = defaultOptions();
        options.setMaxInflightQueue(1);
        options.setPublishMaxRetries(3);

        MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);

        session.start();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.CONNECTED);

        String topic = "test/retry-qos2/" + System.currentTimeMillis();

        var f1 = session.publish(topic, Buffer.buffer("qos2-a"), MqttQoS.EXACTLY_ONCE, false, false)
                .toCompletionStage().toCompletableFuture();
        var f2 = session.publish(topic, Buffer.buffer("qos2-b"), MqttQoS.EXACTLY_ONCE, false, false)
                .toCompletionStage().toCompletableFuture();

        assertThat(f1.get(10, TimeUnit.SECONDS)).isNotNull();
        assertThat(f2.get(10, TimeUnit.SECONDS)).isNotNull();

        session.stop();
        await().atMost(10, TimeUnit.SECONDS)
                .until(() -> session.getState() == SessionState.DISCONNECTED);
    }

    @Test
    void pendingPublishesResentAfterReconnect() throws Exception {
        // Use a dedicated broker to avoid disrupting other tests
        try (GenericContainer<?> broker = new GenericContainer<>("eclipse-mosquitto:2.0")
                .withExposedPorts(1883)
                .withCopyFileToContainer(MountableFile.forClasspathResource("mosquitto.conf"),
                        "/mosquitto/config/mosquitto.conf")
                .waitingFor(Wait.forListeningPort())
                .waitingFor(Wait.forLogMessage(".*mosquitto .* running.*", 1))) {
            broker.start();
            MqttTestBase.awaitForMosquittoToBeReady(broker);

            MqttClientSessionOptions options = new MqttClientSessionOptions();
            options.setHostname(broker.getHost());
            options.setPort(broker.getMappedPort(1883));
            options.setCleanSession(false);
            options.setClientId("resend-test-" + System.currentTimeMillis());
            options.setPublishMaxRetries(5);
            options.setKeepAliveInterval(2);
            ConstantReconnectDelayOptions reconnect = new ConstantReconnectDelayOptions();
            reconnect.setDelay(Duration.ofSeconds(1));
            options.setReconnectDelay(reconnect);

            MqttClientSession session = MqttClientSession.create(vertx.getDelegate(), options);
            List<SessionState> states = new CopyOnWriteArrayList<>();
            session.sessionStateHandler(e -> states.add(e.getSessionState()));

            session.start();
            await().atMost(10, TimeUnit.SECONDS)
                    .until(() -> session.getState() == SessionState.CONNECTED);

            String topic = "test/resend/" + System.currentTimeMillis();

            // Pause the broker to prevent PUBACKs from arriving
            broker.getDockerClient().pauseContainerCmd(broker.getContainerId()).exec();
            try {
                var f = session.publish(topic, Buffer.buffer("will-retry"), MqttQoS.AT_LEAST_ONCE, false, false)
                        .toCompletionStage().toCompletableFuture();

                // Wait for the connection to drop
                await().atMost(30, TimeUnit.SECONDS)
                        .until(() -> states.contains(SessionState.DISCONNECTED));

                // Unpause the broker so reconnect can succeed
                broker.getDockerClient().unpauseContainerCmd(broker.getContainerId()).exec();

                // Session should reconnect and resend the pending publish
                await().atMost(30, TimeUnit.SECONDS)
                        .until(() -> session.getState() == SessionState.CONNECTED);

                Integer packetId = f.get(30, TimeUnit.SECONDS);
                assertThat(packetId).isNotNull();
            } finally {
                try {
                    broker.getDockerClient().unpauseContainerCmd(broker.getContainerId()).exec();
                } catch (Exception ignored) {
                }
            }

            session.stop();
            await().atMost(10, TimeUnit.SECONDS)
                    .until(() -> session.getState() == SessionState.DISCONNECTED);
        }
    }

    @Test
    void publishMaxRetriesOptionDefault() {
        MqttClientSessionOptions options = new MqttClientSessionOptions();
        assertThat(options.getPublishMaxRetries()).isEqualTo(MqttClientSessionOptions.DEFAULT_PUBLISH_MAX_RETRIES);
        assertThat(options.getPublishMaxRetries()).isEqualTo(3);
    }

    @Test
    void publishMaxRetriesOptionCopied() {
        MqttClientSessionOptions original = new MqttClientSessionOptions();
        original.setPublishMaxRetries(7);
        MqttClientSessionOptions copy = new MqttClientSessionOptions(original);
        assertThat(copy.getPublishMaxRetries()).isEqualTo(7);
    }
}
