= Integration with Apache Camel

The Camel connector adds support for Apache Camel to Reactive Messaging.

https://camel.apache.org/[Camel] is an open source integration framework let you integrate various systems consuming or producing data.
Camel implements the Enterprise Integration Patterns and provides several hundred of components used to access databases, message queues, APIs or basically https://camel.apache.org/components/latest/[anything under the sun].

== Introduction

Camel is not a messaging broker.
But, it allows your Reactive Messaging application to retrieve data from almost anything and send data to almost anything.

So if you want to send Reactive Messaging `Message` to Telegram or retrieve data from Salesforce or SAP, this is the connector you need.

One of the Camel cornerstone is the `endpoint` and its `uri` encoding the connection to an external system.
For example, `file:orders/?delete=true&charset=utf-8` instructs Camel to read the files from the `orders` directory.
URI format and parameters are listed on the component documentation, such as the https://camel.apache.org/components/latest/file-component.html[File component].

include::installation.adoc[]
include::inbound.adoc[]
include::outbound.adoc[]
include::processor.adoc[]
include::use-camel-api.adoc[]


