[#camel-inbound]
== Retrieving data using Camel

Camel provides many components.
To keep this documentation focused on the integration with Camel, we use the https://camel.apache.org/components/latest/file-component.html[File component].
This component let use read files from a directory.
So the connector configured with this component creates a `Message` for each file located in the directory.
As soon as a file is dropped in the directory, a new `Message` is created.

=== Example

Let's imagine you want to read the files from the `orders` directory and send them to the `files` channel.
Configuring the Camel connector to gets the _file_ from this directory only requires 2 properties:

[source]
----
mp.messaging.incoming.files.connector=smallrye-camel       # <1>
mp.messaging.incoming.files.endpoint-uri=file:orders/?delete=true&charset=utf-8 # <2>
----
1. Sets the connector for the `files` channel
2. Configures the `endpoint-uri`

Then, your application receives `Message<GenericFile<File>>`.

NOTE: The Camel File component produces `org.apache.camel.component.file.GenericFile` instances. You can retrieve the actual `File` using `getFile()`.


You can consumes the payload directly:

[source, java]
----
include::example$inbound/CamelFileConsumer.java[]
----

You can also retrieve the `Message<GenericFile<File>>`:

[source, java]
----
include::example$inbound/CamelFileMessageConsumer.java[]
----

=== Deserialization

Each Camel component is producing specific objects.
As we have seen, the File component produces `GenericFile`.

Refer to the component documentation to check which type is produced.

=== Inbound Metadata

The Camel connector does not provide inbound metadata.

=== Configuration Reference

include::connectors:partial$META-INF/connector/smallrye-camel-incoming.adoc[]

