[#camel-outbound]
== Sending data with Camel

You can use the Camel connector to send data to almost any type of system.

To keep this document focused on the Camel connector, we use the Camel File component.
However, the connector can be used with any Camel component.

=== Example

Let's imagine you want to write generated prices into files.
Configure your application to write the messages from the `prices` channel into a files as follows:

[source]
----
mp.messaging.outgoing.prices.connector=smallrye-camel # <1>
mp.messaging.outgoing.prices.endpoint-uri=file:prices/?fileName=${date:now:yyyyMMddssSS}.txt&charset=utf-8
----
1. Sets the connector for the `prices` channel
2. Configure the `endpoint-uri` to write into files in the `prices` directory

IMPORTANT: Depending on your implementation of MicroProfile Reactive Messaging, the `$` may need to be escaped as follows: `$${...}`

Then, your application must send `Message<String>` to the `prices` channel.
It can use `String` payloads as in the following snippet:

[source, java]
----
include::example$outbound/CamelPriceProducer.java[]
----

Or, you can send `Message<Double>`:

[source, java]
----
include::example$outbound/CamelPriceMessageProducer.java[]
----

=== Serialization

The serialization is handled by the Camel component.
Refer to the Camel documentation to check which payload type is supported by the component.

=== Outbound Metadata

When sending `Messages`, you can add an instance of {javadoc-base}/apidocs/io/smallrye/reactive/messaging/camel/OutgoingExchangeMetadata.html[`OutgoingExchangeMetadata`] to the message metadata.
You can then influence how the outbound Camel `Exchange` is created, for example by adding properties:

[source, java]
----
include::example$outbound/CamelOutboundMetadataExample.java[tag=code]
----

=== Acknowledgement

The incoming messages are acknowledged when the underlying Camel exchange completes.

=== Configuration Reference

include::connectors:partial$META-INF/connector/smallrye-camel-outgoing.adoc[]
