[#kafka-avro-configuration]
== Using Apache Avro serializer/deserializer

If you are using https://avro.apache.org/[Apache Avro] serializer/deserializer, please note the following properties:

=== For https://docs.confluent.io/current/schema-registry/serdes-develop/serdes-avro.html[Confluent] Schema Registry

==== Consumer

[options="header"]
|===
| "value.deserializer" | "io.confluent.kafka.serializers.KafkaAvroDeserializer"
| "schema.registry.url" | "http://<your_host>:<your_port>/"
| "specific.avro.reader" | true
|===

Example:
[source]
----
mp.messaging.incoming.[channel].value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.[channel].schema.registry.url=http://<your_host>:<your_port>/
mp.messaging.incoming.[channel].specific.avro.reader=true
----

==== Producer

[options="header"]
|===
| "value.serializer" | "io.confluent.kafka.serializers.KafkaAvroSerializer"
| "schema.registry.url" | "http://<your_host>:<your_port>/"
|===

Example:
[source]
----
mp.messaging.outgoing.[channel].value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.[channel].schema.registry.url=http://<your_host>:<your_port>/
----

=== For https://github.com/Apicurio/apicurio-registry[Apicurio] Schema Registry

==== Consumer

[options="header"]
|===
| "value.deserializer" | "io.apicurio.registry.utils.serde.AvroKafkaDeserializer"
| "apicurio.registry.url" | "http://<your_host>:<your_port>/api"
| "apicurio.registry.avro-datum-provider" | "io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider"
|===

Example:
[source]
----
mp.messaging.incoming.[channel].value.deserializer=io.apicurio.registry.utils.serde.AvroKafkaDeserializer
mp.messaging.incoming.[channel].apicurio.registry.url=http://<your_host>:<your_port>/api
mp.messaging.incoming.[channel].apicurio.registry.avro-datum-provider=io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
----

==== Producer

[options="header"]
|===
| "value.serializer" | "io.apicurio.registry.utils.serde.AvroKafkaSerializer"
| "apicurio.registry.url" | "http://<your_host>:<your_port>/api"
| "apicurio.registry.avro-datum-provider" | "io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider"
| "apicurio.registry.global-id" | "io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy"
| "apicurio.registry.artifact-id" | "io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy"
|===

Example:
[source]
----
mp.messaging.outgoing.[channel].value.serializer=io.apicurio.registry.utils.serde.AvroKafkaSerializer
mp.messaging.outgoing.[channel].apicurio.registry.url=http://<your_host>:<your_port>/api
mp.messaging.outgoing.[channel].apicurio.registry.avro-datum-provider=io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
mp.messaging.outgoing.[channel].apicurio.registry.global-id=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
mp.messaging.outgoing.[channel].apicurio.registry.artifact-id=io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
----
