[#kafka-consumer-rebalance-listener]
=== Consumer Rebalance Listener

An implementation of the consumer re-balance listener can be provided which affords us fine grain controls of the assigned
offset. Common uses are storing offsets in a separate store to enable deliver exactly-once semantics, and starting from
a specific time window.

Whenever the topic partitions assigned method is called the consumer will pause. It will only resume once the returned
Uni succeeds. In the case of failure it will retry until success or until the consumer session times out in which case
it will resume again forcing a new consumer re-balance.

==== Example

In this example we will set-up a consumer that always starts on messages from at most 10 minutes ago. First we need to provide
a bean managed implementation of `io.smallrye.reactive.messaging.kafka.KafkaConsumerRebalanceListener` annotated with
`javax.inject.Named`. We then must configure our inbound connector to use this named bean.

[source, java]
----
include::example$inbound/KafkaRebalancedConsumerRebalanceListener.java[]
----

[source, java]
----
include::example$inbound/KafkaRebalancedConsumer.java[]
----

To configure the inbound connector to use the provided listener we either set the consumer rebalance listener's name:

* `mp.messaging.incoming.rebalanced-example.consumer-rebalance-listener.name=rebalanced-example.rebalancer`

Or have the listener's name be the same as the group id:

* `mp.messaging.incoming.rebalanced-example.group.id=rebalanced-example.rebalancer`

Setting the consumer re-balance listener's name takes precedence over using the group id.
