= Testing without the infrastructure

It's not rare to have to test your application but deploying the infrastructure can be cumbersome.
While Docker or Test Containers have improved the the testing experience, you may want to _mock_ this infrastructure.

SmallRye Reactive Messaging proposes an _in-memory_ connector for this exact purpose.
It allows switching the connector used for a channel with an _in-memory_ connector.
This connector can then provide a way to send messages for incoming channels, or check the received messages for outgoing
channels.

To use the _in-memory_ connector, you need to add the following dependency to your project:

[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-reactive-messaging-in-memory</artifactId>
  <version>{version}</version>
  <scope>test</scope>
</dependency>
----

Then, in a test, you can do something like:

[source,java]
----
// ...
import io.smallrye.reactive.messaging.connectors.InMemoryConnector;
import io.smallrye.reactive.messaging.connectors.InMemorySource;
import io.smallrye.reactive.messaging.connectors.InMemorySink;
// ...

@Test
class MyTest {

    // 1. Switch the channels to the in-memory connector:
    @BeforeAll
    public static void switchMyChannels() {
        InMemoryConnector.switchChannelToInMemory("prices", "processed-prices");
    }

    // 2. Don't forget to reset the channel after the tests:
    @AfterAll
    public static void revertMyChannels() {
        InMemoryConnector.clear();
    }

    // 3. Inject the in-memory connector in your test,
    // or use the bean manager to retrieve the instance
    @Inject @Any
    InMemoryConnector connector;

    @Test
    void test() {
      // 4. Retrieves the in-memory source to send message
      InMemorySource<Integer> prices = connector.source("prices");
      // 5. Retrieves the in-memory sink to check what is received
      InMemorySink<Integer> results = connector.sink("processed-prices");

      // 6. Send fake messages:
      prices.send(1);
      prices.send(2);
      prices.send(3);

      // 7. Check you have receives the expected messages
      assertThat(results.received()).hasSize(3)
        .extracting(Message::getPayload).containsExactly(2, 3, 4);
    }
}
----

[IMPORTANT]
====
This connector has been designed for testing purpose only.
====
