== Broadcast

[IMPORTANT]
.Experimental
====
`@Broadcast` is an experimental feature.
====

By default, messages transiting in a channel are only dispatched to a single consumer.
Having multiple consumers is considered as an error, and is reported at deployment time.

The {javadoc-base}/io/smallrye/reactive/messaging/annotations/Broadcast.html[`Broadcast`] annotation changes this behavior and indicates that messages transiting in the channel are dispatched to all the consumers.
`@Broadcast` must be used with the `@Outgoing` annotation:

[source, java, indent=0]
----
include::example$broadcast/BroadcastExamples.java[tag=chain]
----

In the previous example, both consumers get the messages.

You can also control the number of consumers to wait before starting to dispatch the messages.
This allows waiting for the complete graph to be weaved:

[source, java, indent=0]
----
include::example$broadcast/BroadcastWithCountExamples.java[tag=chain]
----

== Use with Emitter

For details on how to use `@Broadcast` with `Emitter` see the xref:emitter/emitter.adoc#emitter-broadcast[documentation].
