[#JMS-outbound]
== Sending messages to JMS

The JMS Connector can send Reactive Messaging `Messages` as JMS Message.

=== Example

Let's imagine you have a `javax.jms.ConnectionFactory` bean exposed and connected to your JMS server.
Don't forget that it's required to use the JMS connector.

Configure your application to write the messages from the `prices` channel into a JMS Message as follows:

[source]
----
mp.messaging.outgoing.prices.connector=smallrye-jms       # <1>
----
1. Sets the connector for the `prices` channel

NOTE: You don't need to set the destination. By default, it uses the channel name (`prices`). You can configure the `destination` attribute to override it.

NOTE: By default the connector uses a `queue`. You can configure it to use a `topic` by setting `destination-type=topic`.

Then, your application must send `Message<Double>` to the `prices` channel.
It can use `double` payloads as in the following snippet:

[source, java]
----
include::example$outbound/JmsPriceProducer.java[]
----

Or, you can send `Message<Double>`:

[source, java]
----
include::example$outbound/JmsPriceMessageProducer.java[]
----

=== Serialization

The connector serializes the incoming message payload into the body of the outgoing JMS Message.

If the payload is a `String` or a primitive type, the payload is encoded as `String` and the `JMSType` is set to the target class.
The `_classname` property is also set.
The JMS Message is a `TextMessage`.

If the payload is a `byte[]`, it's passed as `byte[]` in a JMS `BytesMessage`.

Otherwise, the payload is encoded using JSON-P.
The `JMSType` is set to the target class.
The `_classname` property is also set.
The JMS Message is a `TextMessage`.

For example, the following code serialize the produced `Person` using JSON-B.

[source,java]
----
@Incoming("...")
@Outgoing("my-channel")
public Person sendToJms(...) {
  // ...
  return new Person("bob", 42);
}
----

It requires that the `Person` class can be serialized to JSON.
The classname is passed in the `JMSType` property and `_classname` property.



=== Outbound Metadata

When sending `Messages`, you can add an instance of {javadoc-base}/apidocs/io/smallrye/reactive/messaging/jms/OutgoingJmsMessageMetadata.html[`OutgoingJmsMessageMetadata`] to influence how the message is going to written to JMS.

[source,java,indent=0]
----
include::example$outbound/JmsOutboundMetadataExample.java[tag=code]
----

These metadata allow adding properties but also override the destination.

=== Acknowledgement

Once the JMS message is sent to the JMS server, the message is acknowledged.
Sending a JMS message is a blocking operation.
So, sending is done on a worker thread.

=== Configuration Reference

include::connectors:partial$META-INF/connector/smallrye-jms-outgoing.adoc[]
