= Documentation

This module contains the SmallRye Reactive Messaging documentation.
The documentation is written using https://asciidoctor.org/[Asciidoctor] and https://antora.org/[Antora].

IMPORTANT: This is an unconventional Maven project.

== Structure

=== The content

The documentation sources are in `src/main/doc`.
The files are organized in https://docs.antora.org/antora/2.0/modules/[_modules_]:

* `ROOT` is the main module and contains the getting started and concepts
* Each connector has its own modules, for example `amqp`, `kafka`...
* `connectors` is a special modules containing _partials_ (so piece of content included into pages).
It contains the generated connector attribute tables (in the `META-INF/connector` directory).

Each module is composed as follows:

* pages contains the `adoc` files
* examples contains the code examples
* images contains the images

For each module with _examples_, the example directory (`src/main/doc/modules/<name>/examples`) must be added to the Maven build path using the Maven Build Helper Plugin:

[source, xml]
----
<sources>
  <source>src/main/doc/modules/ROOT/examples</source>
</sources>
----

=== antora.yaml

The `src/main/antora/antora.yaml` file is filtered.
It means that Maven replaces the variable.
This files is copied to `src/main/doc` directory.

=== The connector documentation table

Each connector using `@ConnectorAttribute` provides a _table_ listing the attributes.
These files are copied during the `mvn compile` to `src/doc/modules/connectors/partials/META-INF/connector`.
It means that every time a connector is updated, this file will be updated. So don't forget to commit and push.

== Generating the documentation

You need to install Antora first.
Follow the https://docs.antora.org/antora/2.0/install/install-antora/[installation guide].

Then, run, from the `documentation` directory:

[source, bash]
----
mvn compile # <1>
antora generate target/antora/antora-playbook.yml --clean # <2>
open target/antora/build/site/index.html # <3>
----
<1> Copy the content in target/antora/ and provide a filtered antora-playbook.yml (containing the various Maven variables)
<2> Generate the output
<3> Open the generated `index` page

